### ISSUE TITLE
HTML-Error messages are still not very usefull

### ISSUE THREAD

**Issue by rliebig** [hhucn/webvulnscan#10]
As example, it tried to scan https://github.com/lefnire/habitrpg with webvulnscan and ended up with the following output:

```
Warning: No Content-Type header on http://localhost:3000/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/theron/webvulnscan/webvulnscan/__main__.py", line 18, in <module>
   webvulnscan.main()
  File "webvulnscan/__init__.py", line 141, in main
        run(options, arguments)
  File "webvulnscan/__init__.py", line 48, in run
        for page in urls:
  File "webvulnscan/crawler.py", line 44, in __iter__
        page = self.client.download_page(link, blacklist=self.blacklist)
  File "webvulnscan/client.py", line 89, in download_page
       return Page(url, html, headers, status_code, blacklist)
  File "webvulnscan/page.py", line 18, in __init__
    self.document = self.generate_document()
  File "webvulnscan/page.py", line 26, in generate_document
    return ET.fromstring(self.html, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "webvulnscan/EtreeParser.py", line 49, in close
    return self.tb.close()
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1385, in close
    assert self._last is not None, "missing toplevel element"
AssertionError: missing toplevel element
```

**Comment by rliebig** [comment]
Fixed via 22d3ff2
