### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SIGPIPE'

### ISSUE THREAD

**Issue by niunan** [hhucn/webvulnscan#82]
we can't run the webvulnscan, why?
input : python -m webvulnscan http://www.niunan.net
Error:
`
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\temp\webvulnscan\webvulnscan\__main__.py", line 18, in <module>
    webvulnscan.main()
  File "webvulnscan\__init__.py", line 99, in main
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
AttributeError: 'module' object has no attribute 'SIGPIPE'
`

**Comment by rliebig** [comment]
Sorry for the late answer - I hope that you will still read this. We did never try webvulnscan on windows, so maybe the issue is stemming from there. I will look into this when I have access to a windows installation.

On a another note I recommend that you do not run webvulnscan against a live installation as it can cause same damage on your database entries.
